[2023-03-29T18:56:51.555+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-03-29T18:56:50.384187+00:00 [queued]>
[2023-03-29T18:56:51.568+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-03-29T18:56:50.384187+00:00 [queued]>
[2023-03-29T18:56:51.569+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:56:51.570+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-29T18:56:51.571+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:56:51.580+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-03-29 18:56:50.384187+00:00
[2023-03-29T18:56:51.585+0000] {standard_task_runner.py:55} INFO - Started process 17941 to run task
[2023-03-29T18:56:51.588+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2023-03-29T18:56:50.384187+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp4bv4e8lf']
[2023-03-29T18:56:51.591+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask create_table
[2023-03-29T18:56:51.640+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2023-03-29T18:56:50.384187+00:00 [running]> on host 9dcb783b1f3a
[2023-03-29T18:56:51.683+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T18:56:50.384187+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T18:56:50.384187+00:00
[2023-03-29T18:56:51.690+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-03-29T18:56:51.697+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            )   
        , parameters: None
[2023-03-29T18:56:51.699+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-03-29T18:56:51.707+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230329T185650, start_date=20230329T185651, end_date=20230329T185651
[2023-03-29T18:56:51.762+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-03-29T18:56:51.784+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
