[2023-03-29T18:44:02.124+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-03-29T18:44:00.987028+00:00 [queued]>
[2023-03-29T18:44:02.135+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-03-29T18:44:00.987028+00:00 [queued]>
[2023-03-29T18:44:02.136+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:44:02.137+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-29T18:44:02.138+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:44:02.149+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-03-29 18:44:00.987028+00:00
[2023-03-29T18:44:02.156+0000] {standard_task_runner.py:55} INFO - Started process 17270 to run task
[2023-03-29T18:44:02.160+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2023-03-29T18:44:00.987028+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp395izcd3']
[2023-03-29T18:44:02.163+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask create_table
[2023-03-29T18:44:02.219+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2023-03-29T18:44:00.987028+00:00 [running]> on host 9dcb783b1f3a
[2023-03-29T18:44:02.266+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T18:44:00.987028+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T18:44:00.987028+00:00
[2023-03-29T18:44:02.275+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-03-29T18:44:02.280+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            )   
        , parameters: None
[2023-03-29T18:44:02.282+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-03-29T18:44:02.290+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230329T184400, start_date=20230329T184402, end_date=20230329T184402
[2023-03-29T18:44:02.337+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-03-29T18:44:02.359+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
